language: node_js

node_js:
  - "10"

deploy:
  provider: script
  script: yarn install && yarn run docz:build && yarn run deploy
  keep_history: true
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    branch: master
