language: node_js

node_js:
  - '10'

cache:
  directories:
    - node_modules

script:
  - yarn install
  - yarn docz:build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: .docz/dist
  on:
    branch: master
